set(G2L_IDF_TARGET_PLATFORM "esp32" CACHE STRING "The target platform" FORCE PARENT_SCOPE)
set(G2L_IDF_TARGET_PLATFORM_VARIANT "esp32s3" CACHE STRING "The target platform variant" FORCE PARENT_SCOPE)

set(ESP_TARGET ${target_platform_variant} CACHE STRING PARENT_SCOPE FORCE)
set(CMAKE_TOOLCHAIN_FILE $ENV{IDF_PATH}/tools/cmake/toolchain-${ESP_TARGET}.cmake CACHE PATH PARENT_SCOPE FORCE)