name: CMake

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Unit Tests
      run: cmake --workflow --preset tests -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Run Unit Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --verbose

